# Generated by Django 2.0.5 on 2018-05-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitrakatha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=120)),
                ('shortdescription', models.CharField(max_length=80)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(upload_to='')),
                ('published_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
