# Generated by Django 2.0.5 on 2018-05-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chitrakatha', '0002_mainimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addimage',
            name='content',
        ),
    ]
